blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    # TODO: Update this URL to match your new repository Discussion page
    url: https://github.com/your-username/your-project-name/discussions
    about: Please ask and answer questions here.
